package w10.types;

import w10.Context;
import w10.types.Hook;

/** Options passed to Warp10.listen() */
typedef ListenOptions = {
	port:Int,
	?host:String,
};

/** A route handler function */
typedef RouteHandler = (ctx:Context) -> Void;

/** Server configuration */
typedef ServerConfig = {
	/** Service name */
	?serviceName:String,

	/** Number of accept threads (default: number of CPU cores) */
	?acceptThreads:Int,

	/** Max header size in bytes (default: 8192) */
	?maxHeaderSize:Int,

	/** Receive buffer size (default: 4096) */
	?recvBufferSize:Int,

	/** Keep-alive timeout in ms (default: 15000) */
	?keepAliveTimeout:Int,

	/** Max requests per connection (default: 1000) */
	?maxRequestsPerConnection:Int,

	/** Listen backlog (default: 4096) */
	?backlog:Int,

	/** Enable built-in structured JSON logging (default: false) */
	?logging:Bool,
};

/**
 * A route entry stored in the radix trie.
 *
 * Each route carries its own hook chains, snapshotted at registration
 * time from the encapsulation scope (Warp10 instance) that registered it.
 * This enables Fastify-style plugin scoping: hooks added inside a
 * register() block only apply to routes registered within that block.
 */
typedef RouteEntry = {
	handler:RouteHandler,
	onRequestHooks:Array<HookFn>,
	preHandlerHooks:Array<HookFn>,
	onResponseHooks:Array<HookFn>,
};

/** Result of a route lookup */
typedef RouteMatch = {
	entry:RouteEntry,
	params:Map<String, String>,
};

/**
 * Plugin function signature.
 *
 * A plugin receives the Warp10 app instance and can call
 * addHook(), get(), post(), etc. to configure itself.
 *
 *     app.register(MyPlugin.create({root: "/public"}));
 */
typedef PluginFn = (app:w10.Warp10) -> Void;

/**
 * Route metadata collected during registration for OpenAPI generation.
 *
 * Every call to _addRoute() pushes one of these to the route registry.
 * The macro auto-populates params/querystring schemas from typed handler
 * parameters. Users can enrich entries via Warp10.describe().
 */
typedef RouteInfo = {
	method:HttpMethod,
	path:String,
	?schema:RouteSchema,
};

/**
 * OpenAPI schema annotations for a route.
 *
 * Fields auto-generated by the macro:
 *   - params:      JSON Schema for path parameters (from :param segments)
 *   - querystring: JSON Schema for query parameters (remaining typed params)
 *
 * Fields provided by the user via describe():
 *   - summary, description, tags, operationId, deprecated, hide
 *   - body:     JSON Schema for request body (POST/PUT/PATCH)
 *   - response: Map of status codes to response schemas
 *   - security, consumes, produces
 */
typedef RouteSchema = {
	/** Short summary of the operation */
	?summary:String,

	/** Detailed description (supports markdown) */
	?description:String,

	/** Tags for grouping in documentation */
	?tags:Array<String>,

	/** Unique operation identifier */
	?operationId:String,

	/** Mark as deprecated */
	?deprecated:Bool,

	/** Exclude from OpenAPI output */
	?hide:Bool,

	/** JSON Schema for path parameters (auto-generated from macro) */
	?params:Dynamic,

	/** JSON Schema for query string parameters (auto-generated from macro) */
	?querystring:Dynamic,

	/** JSON Schema for request body */
	?body:Dynamic,

	/** Response schemas keyed by status code: {200: {description:..., schema:...}} */
	?response:Dynamic,

	/** Security requirements for this operation */
	?security:Array<Dynamic>,

	/** Content types this operation consumes */
	?consumes:Array<String>,

	/** Content types this operation produces */
	?produces:Array<String>,
};
